/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class SchemeBasicAuth extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, name=password" })
    password: string;

    @SpeakeasyMetadata({ data: "security, name=username" })
    username: string;
}

export class Security extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    mainAuth: string;
}
