/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Success
 */
export class User extends SpeakeasyBase {
    /**
     * User email address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * User first name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "firstName" })
    firstName?: string;

    /**
     * User last name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lastName" })
    lastName?: string;

    /**
     * User supplied username
     */
    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}
