/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateUserJsonSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    mainAuth: string;
}

export class UpdateUserJsonRequest extends SpeakeasyBase {
    /**
     * Updated user object
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    user: shared.User;

    /**
     * Pretty print response
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=pretty_print" })
    prettyPrint?: boolean;

    /**
     * The name that needs to be updated
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=username" })
    username: string;
}

export class UpdateUserJsonResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
